### ISSUE TITLE
child 没有设置指定大小就会压缩到最小，比如text

### ISSUE THREAD

**Issue by ToZhanChi** [Fliggy-Android-Team/fsuper#3]

**Comment by ToZhanChi** [comment]
text 不指定，child1有widget并且小于child2的尺寸，child2的就会被挤压

**Comment by chenBingX** [comment]
在目前的设计中，对 `child1` 和 `child2` 的位置确定，是基于主要内容区域确定。如设置 `text`、`padding`、或者 `width`、`height` 等。所以主要内容区域是要有一个大小的哦。

**Comment by zhanchi88** [comment]
但是聊天消息框是无大小的 胡伟 创始人兼首席执行官 上海彗韶网络科技有限公司 18500136979 邮箱：huwei250@yeah.net 安徽省合肥市蜀山区望江西路金色名郡首座 签名由 网易邮箱大师 定制 在2020年03月29日 12:33，CoorChice 写道： 在目前的设计中，对 child1 和 child2 的位置确定，是基于主要内容区域确定。如设置 text、padding、或者 width、height 等。所以主要内容区域是要有一个大小的哦。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by ToZhanChi** [comment]
但是聊天消息框是无大小的

**Comment by chenBingX** [comment]
有文字也可以的，相当于设置了大小，需要具体看使用场对属性进行相应的配置哦

**Comment by limhGeek** [comment]
消息列表的时候多行文字会导致maxWidth失效吗？

**Comment by chenBingX** [comment]
理论上 `maxWidth` 会对最大允许宽度限制。在你的场景中发生了失效吗？

**Comment by kcchenkd** [comment]
It seems that maxWidth does not work for me.  The msgBoxWidth is about 2/3 of screen width, so the last message should be wrapped. Any idea? Thanks!

![Capture](https://user-images.githubusercontent.com/13073887/84103177-4e523400-a9e0-11ea-871c-a262ddcef168.PNG)
`FSuper(padding: const EdgeInsets.fromLTRB(16.0, 12.0, 16.0, 12.0),
            maxWidth: _msgBoxWidth,
            backgroundColor: bgColor,
            corner: corner,
            margin: margin,
            text: msg.content))`

**Comment by chenBingX** [comment]
在最新的 `2.0.2` 版本中，这个问题得到了修正。
欢迎保持对 **FWidget** 的关注哦。
